[workspace]
members = [
    "chess",
    "engine",
    "nnue/nnue-eval",
    "nnue/trainer",
    "server",
]
exclude = [
    "www/src/chess-wasm",
]

[profile.release]
lto = true

[profile.test]
opt-level = 3