[package]
name = "engine"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "engine-cli"
path = "src/cli.rs"

[profile.release]
lto = true

[dependencies.chess]
path = "../chess"

[dependencies]
anyhow = "1.0.42"
clap = "2.33.3"